version: '3.9'
services:
  backend:
    build:
      context: .
    depends_on:
      - 'mongo-server'
    ports:
      - '3000:3000'
    env_file:
      - .env.prod
    volumes: 
      - ./src:/usr/src/rota-api/src
  mongo-server:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - '27017:27017'
